### ISSUE TITLE
Area units need to be flexible

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/LANDVIZ#18]
From Charles Maxwell:
Currently, LANDVIZ only accepts integer area (in hectares) for input rasters.  Needs to be flexible, either allowing non-integer hectare size or a different unit of area (such as squared meters).  High priority.

**Comment by bmarron18** [comment]
LANDVIZ PreProcTool has been updated to accept  float values. See Issue #19.
