### ISSUE TITLE
Developer documentation needs updating for new release

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/LANDVIZ#21]

**Comment by bmarron18** [comment]
Detailed information for developers about the LANDVIZ changes and the protocol needed to rebuild LANDVIZ is currently provided in, "README_Rebuild_PreProcTool.txt". JLiem's work log is also included in the repo. Should this info be formally integrated into the Developer Guide.pdf?

**Comment by rmscheller** [comment]
Melissa?

**Comment by bmarron18** [comment]
Developer documentation is provided (see comment 7 Mar); recommend closing issue.
