### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/LANDVIZ#33]
I couldn't install the new version. I used the one in the deploy/installer-windows/ folder.

I tried just installing it, tried uninstalling old version first and then installing it again.  No luck.

![image](https://user-images.githubusercontent.com/7819936/38329716-7f80b07a-3803-11e8-982c-8d5616fb42ae.png)

**Comment by mslucash** [comment]
If you delete the web links in the xml, then it runs.  But then you don't have any hyperlinks, which was supposed to be a feature of this new release.

**Comment by mslucash** [comment]
I tried again.  No luck.   I'm using Windows 7.

I'm using this installer.  Same one as you?
\LANDVIZ\deploy\installer_windows
LandisPreProcToolInstaller.msi

![image](https://user-images.githubusercontent.com/7819936/38373835-fe50f48e-38a6-11e8-92ff-b15e55ca7faa.png)

**Comment by mshukuno** [comment]
I think I figured out.  Did you download the entire project meaning clicking "Clone or download" button on the LANDVIZ GitHub page?  If so, it is the reason why the installer is not working.  The large zip file content could be corrupted when unzipped using Windows Explorer.  Please try downloading the installer only.  Go to the link below and click "**Download**".  Let me know if this works.

[https://github.com/LANDIS-II-Foundation/LANDVIZ/blob/master/deploy/installer_windows/LandisPreProcToolInstaller.msi](url)

**Comment by mshukuno** [comment]
Thank you so much for letting me know.  I am such a bad speller - I installed "spell check" extension for my code editor to eliminate typo problems and typo is fixed now.

I updated my LANDVIZ repository.  If you don't find anything, I will do "Pull request".
